### ISSUE TITLE
Generates class name for decimal numbers in @supports

### ISSUE THREAD

**Issue by olivercoad** [activeguild/vite-plugin-sass-dts#102]
I found this issue when doing an `@supports` for oklch relative color syntax, but simplified it down to its simplest form:

```scss
@supports (--num: 1.5) {
  .myclass {
    display: block;
  }
}
```

```ts
declare const classNames: {
  readonly "5": "5";
  readonly myclass: "myclass";
};
export = classNames;
```
