### ISSUE TITLE
Vite alias settings are not resolved

### ISSUE THREAD

**Issue by aki77** [activeguild/vite-plugin-sass-dts#2]
In the following cases,`Can't find stylesheet to import` errors will occur.
Do you have any solutions?

```scss
@use '@/stylesheets/variables'

.App {
  color: variables.$main-color;
}
```
