### ISSUE TITLE
Some classes being skipped when contain only @media

### ISSUE THREAD

**Issue by Nodman** [activeguild/vite-plugin-sass-dts#41]
Hi and thank you for such a useful plugin!

Recently I noticed that some `.d.ts` files are missing few classes, particulary those which are consists only of @media query:

```css
.input {
  @media (min-width: 768px) {
    max-width: 370px;
  }
}
```

I can open PR with fix if you like
